### ISSUE TITLE
ActivityPub support

### ISSUE THREAD

**Issue by revmischa** [iohzrd/follow#2]
It's a cool idea, how about supporting [ActivityPub](https://www.w3.org/TR/activitypub/)?

Bootstrapping a social network is a very hard task, interoperability is a great way to plug into mastodon lemmy pleroma etc.

**Comment by iohzrd** [comment]
Just looking over it briefly, it seems like my schema isn't too dissimilar.
I'll take a more thorough look at the spec and get back to you.
Thanks for the suggestion.
