### ISSUE TITLE
Error unfollow

### ISSUE THREAD

**Issue by pin240** [iohzrd/follow#3]
Please describe what you were doing when this error happened.

Пытался удалить pin. Не отображаются посты

**Specifications**

- **OS**: win7 x64
- **Follow Version**: 0.2.69
- **Electron Version**: 11.1.1
- **Chrome Version**: 87.0.4280.88

![Скрин2](https://user-images.githubusercontent.com/5054369/103460726-b58f5700-4d29-11eb-8f59-8106a7ea33aa.png)

![Скрин3](https://user-images.githubusercontent.com/5054369/103460758-f8e9c580-4d29-11eb-826a-3a780f2d2e78.png)
 
![Скрин1](https://user-images.githubusercontent.com/5054369/103460654-018dcc00-4d29-11eb-8bf4-f5d0934fff76.png)
**Error**

```
TypeError: Cannot read property 'pins' of undefined
    at M (C:\Users\Celleron_2.4G\AppData\Local\Programs\follow\resources\app.asar\electron-main.js:1:255027)
    at async IpcMainImpl.<anonymous> (C:\Users\Celleron_2.4G\AppData\Local\Programs\follow\resources\app.asar\electron-main.js:1:255656)
```

**Comment by iohzrd** [comment]
looking into it, thanks

**Comment by iohzrd** [comment]
should be fixed.
